// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhapjIuLKO4QGh71J-YYJa3CPKz6VuQw',
    appId: '1:718246493368:web:48d26acfc98363ddb4484d',
    messagingSenderId: '718246493368',
    projectId: 'takecare-9b3c0',
    authDomain: 'takecare-9b3c0.firebaseapp.com',
    storageBucket: 'takecare-9b3c0.firebasestorage.app',
    measurementId: 'G-H698H3R73P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sWM-uV4k2Kr2mUqLd0xvmiKaPmobJGY',
    appId: '1:718246493368:android:938e5932b03b68deb4484d',
    messagingSenderId: '718246493368',
    projectId: 'takecare-9b3c0',
    storageBucket: 'takecare-9b3c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkxa_WixC3qzzbYHBIUZg_obar3_S88U',
    appId: '1:718246493368:ios:486a8761eed6ae63b4484d',
    messagingSenderId: '718246493368',
    projectId: 'takecare-9b3c0',
    storageBucket: 'takecare-9b3c0.firebasestorage.app',
    iosClientId: '718246493368-8eas5und4qt5ie9sv17bqg3n50udkefk.apps.googleusercontent.com',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkxa_WixC3qzzbYHBIUZg_obar3_S88U',
    appId: '1:718246493368:ios:486a8761eed6ae63b4484d',
    messagingSenderId: '718246493368',
    projectId: 'takecare-9b3c0',
    storageBucket: 'takecare-9b3c0.firebasestorage.app',
    iosClientId: '718246493368-8eas5und4qt5ie9sv17bqg3n50udkefk.apps.googleusercontent.com',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEhapjIuLKO4QGh71J-YYJa3CPKz6VuQw',
    appId: '1:718246493368:web:d660e0f4f157505cb4484d',
    messagingSenderId: '718246493368',
    projectId: 'takecare-9b3c0',
    authDomain: 'takecare-9b3c0.firebaseapp.com',
    storageBucket: 'takecare-9b3c0.firebasestorage.app',
    measurementId: 'G-E7WHKJK5ZF',
  );
}
