// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gfcCblso7uvnimUlq9XhMJ2q22wKKwY',
    appId: '1:15492338636:web:8a3ffac583c7e7dbd44369',
    messagingSenderId: '15492338636',
    projectId: 'takecare-01',
    authDomain: 'takecare-01.firebaseapp.com',
    storageBucket: 'takecare-01.firebasestorage.app',
    measurementId: 'G-S939WTGCG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMHRAeu6GFhOBfnPikEysePppfIRI9dw',
    appId: '1:15492338636:android:41c5e4e5dc037df3d44369',
    messagingSenderId: '15492338636',
    projectId: 'takecare-01',
    storageBucket: 'takecare-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlvynXTI7UdZHe7PkUVEjlV09tru1sv4Q',
    appId: '1:15492338636:ios:889d7d096ca669efd44369',
    messagingSenderId: '15492338636',
    projectId: 'takecare-01',
    storageBucket: 'takecare-01.firebasestorage.app',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlvynXTI7UdZHe7PkUVEjlV09tru1sv4Q',
    appId: '1:15492338636:ios:889d7d096ca669efd44369',
    messagingSenderId: '15492338636',
    projectId: 'takecare-01',
    storageBucket: 'takecare-01.firebasestorage.app',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2gfcCblso7uvnimUlq9XhMJ2q22wKKwY',
    appId: '1:15492338636:web:f17d67d1abe7d639d44369',
    messagingSenderId: '15492338636',
    projectId: 'takecare-01',
    authDomain: 'takecare-01.firebaseapp.com',
    storageBucket: 'takecare-01.firebasestorage.app',
    measurementId: 'G-S7PZKFM73J',
  );
}
